"""add candidate professional profile

Revision ID: 1fbebf14bcc3
Revises: df78d5faba1f
Create Date: 2026-08-23 12:25:20.539161

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1fbebf14bcc3"
down_revision: str | Sequence[str] | None = "df78d5faba1f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_profiles",
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("headline", sa.String(length=255), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("years_of_experience", sa.Float(), nullable=True),
        sa.Column("current_job_title", sa.String(length=255), nullable=True),
        sa.Column("current_company", sa.String(length=255), nullable=True),
        sa.Column("current_salary", sa.Integer(), nullable=True),
        sa.Column("expected_salary", sa.Integer(), nullable=True),
        sa.Column("notice_period_days", sa.Integer(), nullable=True),
        sa.Column("highest_qualification", sa.String(length=255), nullable=True),
        sa.Column("career_level", sa.String(length=100), nullable=True),
        sa.Column("work_authorization", sa.String(length=100), nullable=True),
        sa.Column("willing_to_relocate", sa.Boolean(), nullable=False),
        sa.Column("remote_preference", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("candidate_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("candidate_profiles")
    # ### end Alembic commands ###
