"""create job required skills table

Revision ID: e6d60f23c0f3
Revises: 3491e249c05c
Create Date: 2026-08-27 10:29:39.256563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d60f23c0f3'
down_revision: Union[str, Sequence[str], None] = '3491e249c05c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_required_skills',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'skill_id')
    )
    op.create_index('ix_job_required_skills_skill_id', 'job_required_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_required_skills_skill_id', table_name='job_required_skills')
    op.drop_table('job_required_skills')
    # ### end Alembic commands ###
